//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CECodeManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\"Advantage\",\"AdvantageCustomReports\",\"AdvantageWeb\",\"AdvantageCreditCards\",\"Adva" +
            "ntageShared\",\"AdvantageDiscountBase\",\"AdvantageRelay\",\"AdvantageWebAdmin\",\"Advan" +
            "tageSales\",\"AdvantageTaxes\", \"CenterEdgeSiteInfo\"]")]
        public string ActiveRepoList {
            get {
                return ((string)(this["ActiveRepoList"]));
            }
            set {
                this["ActiveRepoList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("430daefd30be5773170211b938dcaa127786b424")]
        public string GitHubToken {
            get {
                return ((string)(this["GitHubToken"]));
            }
            set {
                this["GitHubToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CenterEdge")]
        public string GitHubRepoOwner {
            get {
                return ((string)(this["GitHubRepoOwner"]));
            }
            set {
                this["GitHubRepoOwner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RobRobertsCE")]
        public string GitHubUserName {
            get {
                return ((string)(this["GitHubUserName"]));
            }
            set {
                this["GitHubUserName"] = value;
            }
        }
    }
}
